Locales['en'] = {
    cmdcreategarage = 'Create Garage',
    cmdgaragesetting = 'Create Setting',
    noaccess = "You don't have permission to do this!",
    setpos = "Set Position",
    remove = "Remove",
    removeconfirm = "Are you sure you want to remove this garage?",

    garageinfo = 'Garage Info',
    garagename = "Garage Name",
    garagetype = 'Garage Type',
    garagetype1 = 'Car Garage',
    garagetype2 = 'Boat Garage',
    garagetype3 = 'Heli Garage',
    garagetype4 = 'Plane Garage',
    enableparkingfee = 'Enable Parking Fee',
    parkingfeehour = 'Hourly Fee (If Parking Fee Enabled)',
    realparking = 'Real Parking',
    enableparkinglimit = 'Enable Parking Limit',
    maxvehicle = 'Max Vehicle (If Parking Limit Enabled)',
    transferfee = 'Transfer Fee',
    enableblip = 'Enable Blip',
    setrepos = 'Set Reposition',

    currentgarage = '%s',
    carnamegarage = '%s (%s)',
    accesspark = '[E] - Park',
    accessgarage = '[E] - Garage',
    novehicle = "You don't have any vehicle!",
    garagedescription = "Plate: %s | Fuel : %s%% | Body Health: %s%% | Engine Health: %s%% | Dirt: %s%%",
    nospawn = 'No empty space!',
    notwowner = "You don't own this vehicle!",
    garageempty = "You don't have any vehicle in this garage!",

    fuel = "Fuel Level: %s%%",
    bhealth = "Body Health: %s%%",
    ehealth = "Engine Health: %s%%",
    dirt = "Dirt Level: %s%%",

    drive = "Drive [%s]",
    garages = "Garages",
    garagetransfer = "Transfer Garage",
    fee = " (Fee: $%s)",
    parkingfee = "Parking Fee: $%s",
    select = "Select",
    nootthergarage = "There are no other garage!",
    notmoney = "Not enough money in your bank!",
    notmoneyreal = "Not enough money in your bank. You need $%s!",
    gtransfersuccess = "Garage transfer successful",

    state = "State: %s",
    parked = "Parked",
    impound = "Impound",
    seized = "Seized",

    notparked = "This vehicle is not parked in this garage!",
    notgarage = "This vehicle is not in the garage!",
    vehicleseized = "This vehicle has been seized by police!",

    incompgarage = "Incompatible Garage!",
    setimpoundfee = "Set Impound Fee",
    isimpound = "Is Impound",
    paynow = "Pay Now: $%s",
    paysuccess = "You Paid $%s",
    impoundfee = "Impound Fee: $%s",
    fine = "Fine: $%s",
    vexist = "A vehicle with his plate number has been found outside. Check your minimap.",

    blipcar = "Car Garage",
    blipboat = "Boat Garage",
    blipheli = "Heli Garage",
    blipplane = "Plane Garage",

    exist = "A Garage already exists with this name!",
    garagefull = "No empty space available in this garage!",
    deleteconfirm = "Are you sure you want to remove %s",

}
