Locales['en'] = {
    cmdcreategarage = 'Sukurti garažą',
    cmdgaragesetting = 'Sukurti nustatymus',
    noaccess = "Jūs neturite leidimo tai daryti!",
    setpos = "Nustatykite poziciją",
    remove = "Pašalinti",
    removeconfirm = "Ar tikrai norite pašalinti šį garažą?",

    garageinfo = 'Garažo informacija',
    garagename = "Garažo pavadinimas",
    garagetype = 'Garažo tipas',
    garagetype1 = 'Automobilių garažas',
    garagetype2 = 'Valčių garažas',
    garagetype3 = 'Sraigtasparnių garažas',
    garagetype4 = 'Lėktuvų garažas',
    enableparkingfee = 'Įjungti stovėjimo mokestį',
    parkingfeehour = 'Valandinis mokestis (jei įjungtas automobilių stovėjimo mokestis)',
    realparking = 'Tikra automobilių stovėjimo aikštelė',
    enableparkinglimit = 'Įgalinti parkavimo limitą',
    maxvehicle = 'Maksimalus transporto priemonės skaičius (jei įjungtas stovėjimo apribojimas)',
    transferfee = 'Pervedimo mokestis',
    enableblip = 'Įgalinti Blip',
    setrepos = 'Set Reposition',

    currentgarage = '%s',
    carnamegarage = '%s (%s)',
    accesspark = '[E] – parkuoti',
    accessgarage = '[E] – garažas',
    novehicle = "Jūs neturite jokios transporto priemonės!",
    garagedescription = "Numeriai: %s | Degalai : %s%% | transporto būklė: %s%% | Variklio būklė: %s%% | Nešvarumai: %s%%",
    nospawn = 'Tuščios vietos nėra!',
    notwowner = "Jūs nesate šios transporto priemonės savininkas!",
    garageempty = "Šiame garaže neturite jokios transporto priemonės!",

    fuel = "Kuro lygis: %s%%",
    bhealth = "transporto būklė: %s%%",
    ehealth = "Variklio būklė: %s%%",
    dirt = "Nešvarumo lygis: %s%%",

    drive = "Važiuoti [%s]",
    garages = "Garažai",
    garagetransfer = "Garažo perdavimas",
    fee = " (Mokestis: $%s)",
    parkingfee = "Parkavimo mokestis: $%s",
    select = "Pasirinkite",
    nootthergarage = "Nėra kito garažo!",
    notmoney = "Jūsų banke nepakanka pinigų!",
    notmoneyreal = "Nepakanka pinigų jūsų banke. Jums reikia $%s!",
    gtransfersuccess = "Garažo perdavimas sėkmingai",

    state = "Būsena: %s",
    parked = "Priparkuotas",
    impound = "Konfiskuotas",
    seized = "Sulaikytas",

    notparked = "Ši transporto priemonė nėra pastatyta šiame garaže!",
    notgarage = "Šios transporto priemonės nėra garaže!",
    vehicleseized = "Šią transporto priemonę konfiskavo policija!",

    incompgarage = "Netinkamas garažas!",
    setimpoundfee = "Nustatyti konfiskavimo mokestį",
    isimpound = "Yra konfiskuotas",
    paynow = "Mokėti dabar: $%s",
    paysuccess = "Sumokėjote $%s",
    impoundfee = "Konfiskavimo mokestis: $%s",
    fine = "Bauda: $%s",
    vexist = "Automobilis su jo valstybiniu numeriu rastas lauke. Patikrinkite savo mini žemėlapį.",

    blipcar = "Automobilių garažas",
    blipboat = "Valčių garažas",
    blipheli = "Sraigtasparnių garažas",
    blipplane = "Lėktuvų garažas",

    exist = "Garažas tokiu pavadinimu jau egzistuoja!",
    garagefull = "Šiame garaže laisvos vietos nėra!",
    deleteconfirm = "Ar tikrai norite pašalinti %s",

}
