Locales['en'] = {
    housingtype = 'Būsto tipas',
    housinginfo = 'Būsto informacija',
    houseprice = 'Namo kaina',
    houseinv = 'Inventoriaus svoris',
    houseweed = 'Maksimalus žolės augalas',
    setshellexit = 'Nustatykite išėjimo tašką',
    setshellentry = 'Nustatykite įėjimo tašką',
    setboard = 'Nustatykite lentynos tašką',
    setgarage = 'Nustatykite garažo tašką',
    needagent = 'Reikalingas agentas norint įsigyti?',
    agentname = 'Agento vardas (pasirenkama)',
    agentnameplaceholder = 'jūsų vardas',
    agentphone = 'Agento telefono numeris (pasirinktinai)',
    agentphoneplaceholder = 'Telefono numeris',
    agentnotice = 'Pranešimas (pasirinktinai)',
    agentnoticeplaceholder = 'Jūsų pranešimas',
    hasgarage = 'Ar yra garažas?',

    blipmy = 'Mano namai',
    blipneighbour = 'Kaimyninis namas',
    blipempty = 'Laisvi namai',
    blipfamily = 'Šeimos namas',

    boardagentname = 'AGENTAS: %s',
    boardphone = 'SKAMBINKITE DABAR: %s',
    boardprice = '$%s',
    boardnotice = '%s',

    enterhouse = '[E] – Įėjimas',
    exithouse = '[E] – Įšėjimas',
    hid = 'HID: #%s',
    visithouse = '[E] – Aplankykite',
    purchaseconfirm = 'Ar norite įsigyti šį namą už %s $?',
    knockdoor = '[E] – durų skambutis',
    options = '[H] – pasirinkimai',
    optiontitle = 'Namo parinktys',
    sellhouse = 'Parduoti namą',

    notenoughcash = 'Nepakanka grynųjų pinigų!',
    notenoughbank = 'Jūsų banke nepakanka pinigų!',

    housesold = 'Jūsų namas parduotas. Gavote $%s',

    managemembers = 'Valdyti narius',
    manageaccess = 'Tvarkyti prieigą',
    addmember = 'Pridėti asmenį',
    removemember = 'Pašalinti asmenį',
    playerid = 'Vartotojo ID',
    playeridplaceholder = 'Žaidėjo serveryje ID',
    playername = 'Vartotojo vardas',
    playernameplaceholder = 'Žaidėjo vardas',
    usernotonline = 'Šio asmens šalia nėra',
    alreadykey = 'Šis asmuo jau turi jūsų namų raktą',
    selectkey = 'Pasirinkite raktą, kurį norite pašalinti',
    keyinventory = 'Inventorius',
    keydoors = 'Durys',
    keygarage = 'Garažas',
    keycam = 'Durų kamera',
    keyfurni = 'Baldai',
    keywardrobe = 'Drabužinė',
    capacity = 'Galimos: %skg\nSvoris: %skg\nVietos: %s',

    speed = '~INPUT_MAP_POI~GREITIS: %s',
    nomoney = 'Nepakanka pinigų',

    doorcam = 'Durų kamera',
    exitcam = "Išėjimo kamera",
    exterior = "Išorė",
    restoredel = "Atkurti ištrintus elementus",
    cleaningmode = "Įjunkite valymo režimą",
    object = "Objektas: %s",
    removeobject = "[E] – Pašalinti objektą",
    movegarage = "Perkelti garažą",
    accessgarage = "[H] – garažas",
    garage = "Garažas",
    notinside = "Ši vieta nėra jūsų būsto teritorijoje",

    openstash = "[E] – Saugykla",
    openwardrobe = "[E] - Drabužių spinta",
    dooroptions = "Durų parinktys",
    reposition = "Automatinis durų padėties keitimas",
    accessinvehicle = "Ar galima pasiekti transporto priemonėje?",
    lockbydefault = "Užrakinti pagal numatytuosius nustatymus",
    rdist = "Perteikimo atstumas",
    idist = "Sąveikos atstumas",
    addanother = "Pridėti dar vienas duris?",
    lock = "[E] – užrakinti",
    unlock = "[E] – atrakinti",
    manage = "[G] – Tvarkyti",
    managetitle = "Tvarkyti prieigą",
    nodooraccess = "Jūs neturite prieigos prie šių durų!",
    noinvaccess = "Jūs neturite prieigos prie šios saugyklos!",
    shelllock = "Užrakintos durys",
    shellunlock = "Atrakintos durys",
    brokenlock = "[E] – Pataisyti užraktą",
    elserob = "Kažkas jau apiplėšė šį namą!",
    nolockpick = "Jūs neturite visrakčio!",
    alreadybroken = "Įsilaužėte pro duris!",
    nomembers = "Jūs neturite namo narių!",

    cmdcreatehouse = "Kurti namą",
    cmddeletehouse = "Išvalyti namą",
    cmdfurniture = "Įrengti savo namus",
    cmdrealestate = "Atidarykite nekilnojamojo turto sąvininko meniu",
    cmdhouserob = "Apiplėšti žaidėjo namus",
    cmdhouseraid = "Įsilaužti į žaidėjo namą",
    cmdexterior = "Panaikinti išorinius objektus",

    notenoughcapacity = "Jūsų namuose nėra tiek daug vietos. Dabar tai yra tik baldai.",
    nopermissiontoplacestorage = "Neturite inventoriaus leidimo. Dabar tai yra tik baldai.",
    nopermissiontodeletestorage = "Jums neleidžiama pašalinti jokios saugyklos!",

    raidprograss = "...",
    robprograss = "...",
    robwarning = "KAŽKAS BANDO ĮSILAUŽTI Į JŪSŲ NAMS #%s",
    robwarningpolice = "KAŽKAS BANDO ĮSILAUŽTI Į NAMĄ",
    raidwarning = "POLICIJA PATEKO Į JŪSŲ NAMĄ #%s",
    robblip = "Namas apiplėštas",
    raidblip = "Namas įsilaužtas",

    nomemberonline = "Nėra mieste namų savininkų!",
    nopermission = "Neturite leidimo atlikti šio veiksmo!",

    doormanage = "Tvarkyti duris",
    doorsetting = "Durų nustatymai",

    sellfurni = "Prekė parduota už %s $",

    canclerent = "Atšaukti nuomą",
    canclerentalert = "Ar tikrai norite atšaukti nuomojamą būstą?",
    buyhouse = "Pirkti namą",
    buyhousedesc = "Kaina: $%s | Talpa: %skg",
    renthouse = "Išsinuomoti Namą",
    renthousedesc = "Kaina: %s litais per savaitę (iš anksto apmokėta) | Talpa: %skg",
    rentconfirm = 'Ar norite išsinuomoti šį namą už %s $?',

    installmenthouse = "Pirkti išsimokėtinai",
    installmenthousedesc = "Atlyginimas: %s litais per savaitę | Pradinis įnašas: $%s | Talpa: %skg | Įmokos: x%s",
    installmentconfirm = 'Ar norite pasirašyti išsimokėjimo sutartį?',

    setuppurchase = 'Nustatyti pirkimą',
    enablepurchase = 'Įjungti pirkimą',

    setuprent = 'Nustatykite nuomą',
    enablerent = 'Įjungti nuomą',
    rentprice = 'Nuomos Kaina',

    setuplabs = 'Nustatyti labs',
    setupweed = 'Nustatyti Žolę',
    setupinstallment = 'Įmokos nustatymas',
    enableinstallment = 'Įgalinti išsimokėjimą',
    installmentprice = 'Kaina išsimokėtinai',
    numinstallment = 'Įmokų skaičius',

    cancleinstallment = 'Atšaukti išsimokėjimo sutartį',
    cancleinstallmentalert = 'Ar tikrai norite atšaukti išsimokėjimo sutartį?',

    plant_stage = '~b~[Etapas]:~s~ %s',
    status_growing = '~g~[Būsena]:~s~ Auga...',
    status_not_growing = '~r~[Būsena]:~s~ Neauga',
    status_ready = '~g~[Būsena]:~s~ Paruošta nuimti derlių',
    fertilize = '~g~[E]~s~ - ~b~Tręšti~s~',
    fertilizing = 'Tręšiama...',
    water = '~g~[E]~s~ - ~b~Vanduo~s~',
    watering = 'Laistoma...',
    spray = '~g~[E]~s~ - ~b~Purškiamas~s~',
    harvest = '~g~[H]~s~ - ~b~derliaus~s~',
    harvesting = 'Derliaus nuėmimas',

    nowater = "Jūs neturite vandens",
    nofertilizer = "Jūs neturite trąšų",
    noseed = "Jūs neturite žolės sėklų",
    maxweed = "Šiam namui nebėra žolės augalų",

    process = "~b~[E]~s~ - ~b~Apdoroti~s~",
    collect = "~b~[E]~s~ - ~b~Surinkite~s~",
    setuplab = "~y~[G]~s~ - ~y~Surinkimas~s~",
    labmanageaccess = "~g~[H]~s~ - ~g~Prieiga~s~",
    selectlab = "Pasirinkite Lab",
    selectlabtype = "Pasirinkite tipą",
    typecollect = "Surinkti",
    typeprocess = "Apdorojimas",
    collecting = "Renkama...",
    processing = "Apdorojama...",
    noinv = "Neužtenka vietos inventoriuje",
    noitem = "Nepakanka %s (%sx)!",

    nocollect = "Šioje lab rinkti negalima",
    noprocess = "Apdorojimas negalimas šioje lab",
    nomorehouse = "Jūs jau turite pakankamai namų",

    noshell = "Neturite jokio apvalkalo",
    loadshellfailed = "Nepavyko įkelti korpuso apvalkalo: %s. Susisiekite su serverio savininku!",
    shellcat = "Apvalkalo kategorija",

}
