Locales['en'] = {
  ['cannot_carry'] = 'Negalite neštis daugiau',
  ['insufficient_funds'] = "Nepakanka pinigų",
  ['bought_item_2'] = "Jūs nusipirkote %s %s",

  --shop
  ['press_to_open'] = 'Paspauskite ~INPUT_CONTEXT~, kad atidarytumėte parduotuvę.',
  ['press_to_open_target'] = 'Atidarykite parduotuvę',
  ['open_shop'] = 'Paspauskite ~g~[E]~s~, kad atidarytumėte ~b~Parduotuvės meniu~s~',
  ['open_management'] = 'Valdymas',
  ['not_money'] = 'Nepakanka pinigų!\Jums reikia daugiau $%s',
  ['stock_empty'] = "Nepakanka šios prekės atsargų", 
  ['how_many_item'] = "Kiek prekių jums reikia $%s/prekė", 
  ['stock_items'] = "Atsargos prekės", 

  --farming
  ['plant_id'] = '~o~[ID]:~s~ %s',
  ['plant_stage'] = '~b~[Etapas]:~s~ %s',
  ['status_growing'] = '~g~[Būsena]:~s~ Auga...',
  ['status_not_growing'] = '~r~[Būsena]:~s~ Neauga',
  ['status_ready'] = '~g~[Būsena]:~s~ Paruošta nuimti derlių',
  ['plant'] = 'Paspauskite ~g~[E]~s~, kad pasirinktumėte ~b~Augalas~s~',
  ['fertilize'] = 'Paspauskite ~g~[E]~s~, kad ~b~Tręštumėte~s~',
  ['spray'] = 'Paspauskite ~g~[E]~s~, kad pasirinktumėte ~b~Purkštumėte~s~',
  ['harvest'] = 'Paspauskite ~g~[H]~s~, norėdami ~b~Nuimti derlių~s~',
  ['planting_notify'] = '~g~ Sodinimas...',
  ['planting_progress'] = 'Sodinti...',
  ['fertilizing_notify'] = '~g~Trąšų naudojimas...',
  ['fertilizing_progress'] = 'Trąšų naudojimas...',
  ['spraying_notify'] = 'Naudojamas purškimas...',
  ['spraying_progress'] = 'Naudojamas purškimas...',
  ['harvesting_notify'] = 'Žolės derlius...',
  ['harvesting_progress'] = 'Žolės derlius...',
  ['open_process'] = 'Paspauskite ~g~[E]~s~, kad atidarytumėte ~b~Apdorojimo meniu~s~',
  ['open_process_target'] = 'Atidarykite apdorojimo meniu',
  ['processing_notify'] = 'Apdorojama %s...',
  ['processing_progress'] = 'Apdorojama %s...',
  ['not_enough'] = 'Neužtenka %s',
  ['item_required'] = 'Reikalingas %sx %s!',
  ['you_get'] = 'Jūs gaunate %sx %s',
  ['stock_farm'] = '~g~Atsargos:~s~ %s',
  ['stock_farm_multi'] = 'Paspauskite ~g~[E]~s~, kad atidarytumėte ~b~Atsargų Meniu~s~',
  ['stock_farm_multi_target'] = 'Atidarykite atsargų meniu',

  --Job
  ['not_money_society'] = 'Jūsų parduotuvėje nepakanka pinigų!\nJums reikia daugiau $%s',
  ['open_boss'] = 'Paspauskite ~g~[E]~s~, kad atidarytumėte ~b~Boss Menu~s~',
  ['open_boss_target'] = 'Atidarykite boso meniu',
  ['number_error'] = 'Turi būti skaičius',
  ['put_in'] = 'Įdėkite į parduotuvę',
  ['put_out'] = 'Išimkite iš parduotuvės',
  ['change_price'] = 'Keisti prekės kainą',
  ['stock'] = 'Atsargos: %s',
  ['price'] = 'Kaina: %s',
  ['just_put_in'] = 'Jūs ką tik įdėjote %sx %s parduotuvėje',
  ['just_put_out'] = 'Jūs ką tik išėmėte %sx %s iš parduotuvės',
  ['not_enough_shop_item'] = 'Jūsų parduotuvėje nepakanka %s',
  ['price_change'] = 'Kainos pasikeitimas iš %s į $%s',
  ['rank_not_allowed'] = 'Jūsų rangui neleidžiama atlikti šio veiksmo!',
}
