Locales['en'] = {
    unknowndeath = 'Save ar NPC',
    bleedoutin = 'Nukraujuosite po ~r~%s minučių %s sekundžių~s~',
    braindeadin = 'Smegenys mirs po ~r~%s minučių %s sekundžių~s~',
    respawnavailable = 'Atnaujinti galėsite po ~g~%s minučių %s sekundžių~s~',
    respawn = 'Laikykite nuspaudę ~g~[E]~s~, kad atsigautumėte ~g~%ss~s~',
    respawnmenutitle = 'Ligoninės',
    nomoney = 'Nepakanka pinigų!',
    bedfull = 'Visos lovos užimtos. Laukite laisvos vietos...',
    gettinghelp = '~g~Gaunate pagalbos, liko ~b~%s sekundės!',

    elevator = 'Liftas',
    elevatoraccess = '[E] – liftas',

    onparacetamol = 'Tu jau išgėrei tabletę. Palaukite %ss, kad paimtumėte kitą.',
    ontakeparacetamol = 'Išgėrei tabletę. Tai užtruks %ss, kad sumažintumėte skausmą.',
    takingparacetamol = 'Paracetamolio vartojimas...',
    severeinjury = "Jūs turite sunkų sužalojimą, kurio negalite gydyti paracetamoliu. Atėjo laikas apsilankyti pas gydytoją.",
    severeinjuries = "Jūs turite keletą sunkių sužalojimų, kurių negalite išgydyti paracetamoliu. Atėjo laikas apsilankyti pas gydytoją.",
    noneedparacetamol = "Jūs neturite jokių žaizdų, kurias reikėtų išgydyti",

    damage_notify_head = "Jūs patyrėte galvos traumą ir tai turi įtakos jūsų regėjimui!",
    damage_notify_arms = "Jūs susižeidėte ranką ir tai turi įtakos jūsų šaudymo ir vairavimo gebėjimams!",
    damage_notify_chest = "Jūs kraujuojate dėl krūtinės traumos!",
    damage_notify_legs = "Jūs susižeidėte koją ir tai turi įtakos ėjimo greičiui ir vairavimo gebėjimui!",

    onbandage = "Tvarstis suteikia laikiną palengvėjimą. Bet tai truks neilgai!",

    usebandage = "Uždedamas bintas...",
    alreadyhealing = "Ši kūno dalis jau gyja...",

    takingmorphine = "Vartojate morfiną...",
    tookmorphine30 = "Išgėrei 30 mg morfijaus. Tai palengvina stiprų skausmą!",
    tookmorphine10 = "Išgėrei 10 mg morfijaus. Tai palengvina skausmą!",
    noseverepain = "Jūs neturite stipraus skausmo!",
    nosevereormoderatepain = "Jūs neturite vidutinio ar stipraus skausmo!",
    alreadymorphine = "Jūs jau vartojate morfijų!",

    usingfirstaid = "Naudojate pirmosios pagalbos rinkinį...",
    usingmedkit = "Naudojate medicininės pagalbos rinkinį...",
    tookfirstaid = "Panaudojote pirmosios pagalbos rinkinį, žaizdos gyja...",
    tookmedkit = "Panaudojote medicininės pagalbos rinkinį, jūsų žaizdos gyja...",
    woundsalreadyhealing = "Jūsų žaizdos jau gyja...",

    examine      = "Apžiūrėkite pacientą",
    examinehead  = "Apžiūrėkite galvą",
    examinechest = "Apžiūrėkite krūtinę",
    examinearms  = "Apžiūrėkite rankas",
    examinelegs  = "Apžiūrėkite kojas",

    damagehead  = "Pažeista galva: %s",
    damagechest = "Pažeista krūtinė: %s",
    damagelarm  = "Pažeista Kairė ranka: %s",
    damagelleg  = "Pažeista Kairė koja: %s", 
    damagerarm  = "Pažeista dešinė ranka: %s",
    damagerleg  = "Pažeista dešinė koja: %s",

    applyneckbrace  = "Uždėkite kaklo įtvarą",
    applybodybandage = "Uždėkite korpuso tvarstį",
    applyarmbrace  = "Uždėkite rankos įtvarą",
    applylegbrace  = "Uždėkite kojos įtvarą",

    notenough  = "Neturi %s",

    givemorphine30  = "Duoti 30 mg morfino",

    applylegbrace  = "Uždėkite tvarstį",
    xray  = "Rentgeno skenavimas",

    addtostretcher  = "Užkelti ant neštuvų",
    addtowheelchair  = "Pasodinti į vežimėlį",
    addinbed  = "Paguldyti į lovą",
    removefromstretcher  = "Nukelti nuo neštuvų",
    removefromwheelchair  = "Išlaipinti iš vežimėlio",
    move = "Perkelkite",
    pickup  = "Paimkite",
    getin  = "Įeikite",
    alreadybed  = "Kažkas jau guli lovoje!",
    place  = "[E] – vieta",
    drop  = "[E] – nuleisti",
    leave  = "[E] – išeiti",

    givesaline  = "Duokite fiziologinio tirpalo",
    removesaline  = "Pašalinkite fiziologinį tirpalą",
    givesalinenotify  = "Fiziologinis tirpalas palaiko jūsų sveikatą",

    addstretcher  = "Padėti neštuvus",
    addwheelchair  = "Padėti vežimėlį",
    removestretcher  = "Panaikinti neštuvus",
    removewheelchair  = "Panaikinti vežimėlį",

    givecpr  = "Gaivinimas",
    revive  = "Pagydymas",
    giveadancedcpr  = "Pažangus gaivinimas",
    cprfailed  = "Gaivinimas nesėkmingas! Naudokite krūtinės ląstos suspaudimo įtaisą",
    checkin  = "Užsiregistruokite $%s",
    checkingin  = "Registruojama...",
    enoughems  = "Medikų yra pakankamai!",
    open  = "Atidaryti",
    carry  = "Nešti",
    medicalbag = 'Medicininis krepšys',
    medicinebox = 'Medicinos dėžė',
    pharmacy = 'Vaistinė',
    price = '$%s',

    notrankaccess = 'Jūsų kvalifikacija tam neturi leidimo',
    notonduty = 'Jūs nesate darbe!',

    bossaction = 'Direktoriaus (-ės) meniu',

    garage = 'Ligoninės garažas',
    garagedesc = 'Įsibėgėjimas: %s | Greitis: %s | Stabdymas: %s',
    egarage = '[E] – garažas',
    eparkmod = '[E] – parkuoti \n[G] – papildyti \n[H] – lipdukai',
    modification = 'Modifikacijos',
    extra = 'Papildyti %s',
    livery = 'Lipdukai %s',
    spawnnotclear = 'Transporto išvarymo vieta nėra tuščia!',

    suicideweapon = "**%s** 'nusižudė' (*%s* – *%s*)",
    suicideevent  = "**%s** 'nusižudė' (*%s*)",
    suicidplayer  = "**%s** `nusižudė`",

    aiweapon  = "**%s** buvo „%s“ (*%s*), **AI**",
    aievent   = "**%s** buvo `%s` by **AI**",
    aiother   = "**%s** buvo 'nužudytas' by **AI**",

    playerweapon   = "**%s** buvo `%s` (*%s*) by **%s**",
    playerevent   = "**%s** buvo `%s` by **%s**",
    playerother   = "**%s** buvo 'nužudytas' by **%s**",

    unknownweapon   = "**%s** buvo `%s` (*%s*) by **Unknown**",
    unknownevent   = "**%s** buvo `%s` by **Unknown**",
    unknownother   = "**%s** buvo 'nužudytas' by **Unknown**",

    payment   = "Jūs gavote $%s už šį gydymą.",

    distresssignal   = 'Norėdami išsiųsti nelaimės signalą, paspauskite ~g~[G]~s~',
    nodistress   = "Nerasta nelaimės įspėjimo!",
    dispatch   = "Išsiuntimas",
    dispatchaccepted   = "Jūsų nelaimės signalas gautas. Medikai jau pakeliui.",
    dispatchalert = '[10-47] Reikia medicininės pagalbos %s, %s',
    waypoint = 'Kelio taškas pažymėtas jūsų GPS',

    revivecmd = 'Atgaivinti žaidėją',
    killcmd = 'Nužudyti žaidėją',
    reviveall = 'Atgaivinti visus žaidėjus',
    playerid = 'Žaidėjo ID',
    skellyfix = 'Prikelti lavoną',
    skellyfixall = 'prikelti visus lavonus',

    locker = 'Spintelė',
    keylocker = '[E] – spintelė',
    lockeroutfits = 'Drabužinė',
    regularoutfit = 'Asmeninė apranga',
    wardrobeoutfits = 'Darbo aprangos',

    onduty = 'Dirbate',
    offduty = 'Nedirbate',
}
